print("hello world")
print("hello world")
print("hello world")
print("hello world")
print("hello world")
print("hello world")
print("hello world")
print("hello world")
print("ff")
print("ff")
print("ff")
print("ff")
print("ff")
print("ff")
print("ff")